In [1]:
import numpy as np

def softmax(x):
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))  # stability
    return e_x / np.sum(e_x, axis=-1, keepdims=True)

def scaled_dot_product_attention(Q, K, V):
    # Step 1: Dot product of Q and Kᵀ
    scores = np.dot(Q, K.T)

    # Step 2: Scale by sqrt(d)
    d_k = K.shape[-1]
    scaled_scores = scores / np.sqrt(d_k)

    # Step 3: Softmax to get attention weights
    attention_weights = softmax(scaled_scores)

    # Step 4: Multiply attention weights by V
    output = np.dot(attention_weights, V)

    return attention_weights, output

# Test inputs
Q = np.array([[1, 0, 1, 0],
              [0, 1, 0, 1]])

K = np.array([[1, 0, 1, 0],
              [0, 1, 0, 1]])

V = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

# Run attention
attn_weights, output = scaled_dot_product_attention(Q, K, V)

# Display results
print("1. Attention Weights:\n", attn_weights)
print("\n2. Output:\n", output)


1. Attention Weights:
 [[0.73105858 0.26894142]
 [0.26894142 0.73105858]]

2. Output:
 [[2.07576569 3.07576569 4.07576569 5.07576569]
 [3.92423431 4.92423431 5.92423431 6.92423431]]
